config/routes.rb
Clubber::Application.routes.draw do

  get "/about" => "home#about"
  get "/contact" => "home#contact"

  devise_for :users

  match "/i/:id" => "qr_items#visit"
  delete "/qr_items/destroy/:id" => "qr_items#destroy", :as => :destroy_qr_item
  match "/qr_items/list(/:type)" => "qr_items#list", :as => :qr_items_list 
  match "/qr_items/:type(/:id)" => "qr_items#item", :as => :qr_item

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :points, :through => :event_points
  has_many :event_points, :dependent => :destroy

  validates :name, :uniqueness => true
  validates_datetime :event_date, :after => lambda { 1.hour.from_now }
end

app/models/event_point.rb
require 'qr_image'

class EventPoint < ActiveRecord::Base
  include QrGenerator
  QR_SIZE = 5

  belongs_to :event
  belongs_to :point

  validates :point_id, :uniqueness => { :scope => [:event_id] }

  after_destroy :delete_code
  after_create  :create_qr_image

  def qr_text
    "#{Clubber::Application.config.protocol}://#{Clubber::Application.config.domain}/p/v/#{self.id}"
  end

  def qr_code
    QrImage.get_code(qr_text, QR_SIZE)
  end

  def qr_path
    "/qr/event_points/#{id}.jpg"
  end

  def visit!
    self.visit_number += 1
    self.save
  end

end

app/models/point.rb
class Point < ActiveRecord::Base
  validates :address, :uniqueness => true

  belongs_to :user
  has_many :events, :through => :events_points
  has_many :event_points, :dependent => :destroy

end

app/models/qr_item.rb
class QrItem < ActiveRecord::Base
  include QrGenerator
  serialize :properties
  belongs_to :user

  after_create :create_qr_image
  after_destroy :delete_code

  def qr_text
    "http://qrit.in/i/#{id}"
  end

  def qr_path
    "/qr/items/#{id}.jpg"
  end

  def prepare
    self.class::PROPERTIES.each do |key|
      instance_eval(<<-METHODS)
        def #{key}
          properties[:#{key}]
        end
        def #{key}=(value)
          properties[:#{key}] = value
        end
      METHODS
    end
  end

  def save_properties!(attributes)
    update_attributes(attributes)
    properties = attributes.slice(self.class::PROPERTIES.map {|p| p.to_s})
    save!
  end

  def properties
    super ? super : self.properties = {} 
  end

end

app/models/simple_text.rb
class SimpleText < QrItem
  PROPERTIES = [:text]
  belongs_to :user

  def item_name
    name
  end

  def qr_data
    properties[:text]
  end
end

app/models/sms_message.rb
class SmsMessage < QrItem
  PROPERTIES = [:phone, :message]
  belongs_to :user

  def item_name
    name.blank? ? properties[:phone] : name
  end

  def qr_text
    "SMSTO:#{phone}:#{message}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :points
  has_many :events

  has_many :qr_items
  has_many :vcards
  has_many :sms_messages
end

app/models/vcard.rb
class Vcard < QrItem
  PROPERTIES = [:first_name, :last_name, :phone, :email]
  serialize :properties
  belongs_to :user

  def item_name
    name.blank? ? "#{properties[:first_name]} #{properties[:last_name]}" : name
  end

  def qr_data
    self.prepare
    "BEGIN:VCARD\nVERSION:2.1\nN:#{last_name};#{first_name};\nTEL;HOME;VOICE:#{phone}\nEMAIL:#{email}\nEND:VCARD"
  end
end

app/models/web_url.rb
class WebUrl < QrItem
  PROPERTIES = [:url]
  belongs_to :user
  def item_name
    name.blank? ? properties[:url] : name
  end

  def get_url
    (properties[:url].include?('://') ? '' : 'http://') + properties[:url]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:visit_point]
  before_filter :set_event

  def index
    @events = current_user.events.sort_by(&:event_date)
  end

  def show
    @points = Point.all - @event.points
  end

  def new
    @event = current_user.events.build 
  end

  def edit
  end

  def create
    @event = current_user.events.build(params[:event])
    if @event.save
      redirect_to(@event, :notice => 'Event was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    if @event.update_attributes(params[:event])
      redirect_to(@event, :notice => 'Event was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @event.destroy
    redirect_to(events_url)
  end

  def add_point
    event_point = @event.event_points.create(:point_id => params[:points])
    redirect_to :action => :show
  end

  def delete_point
    @event.event_points.destroy(params[:event_point_id])
    redirect_to :action => :show
  end

  def visit_point
    @unique = cookies[:visit] ? false : true
    cookies[:visit] = true
    @event_point = EventPoint.where(:id => params[:event_point_id]).first
    @event_point.visit! if @event_point && @unique
    @chance = rand(2) > 0
    render :layout => 'mobile'
  end

  protected

  def set_event
    @event = current_user.events.find(params[:id]) if params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :authenticate_user!, :except => [:visit]
  before_filter :set_points, :only => [:index, :create]
  # GET /points
  # GET /points.xml
  def index
    @point  = Point.new 
  end

  def edit
    @point = current_user.points.where(:id => params[:id]).first
  end

  def create
    @point = current_user.points.build(params[:point])
    if @point.save
      redirect_to(:action => :index)
    else
      render :action => "index"
    end
  end

  def update
    @point = current_user.points.where(:id => params[:id]).first
    if @point.update_attributes(params[:point])
      redirect_to(:action => :index)
    else
      render :action => "edit"
    end
  end

  def destroy
    @point = current_user.points.where(:id => params[:id]).first
    @point.destroy
    redirect_to(points_url)
  end

  protected

  def set_points
    @points = current_user.points(true).sort_by(&:address)
  end

end

app/controllers/qr_items_controller.rb
class QrItemsController < ApplicationController
  before_filter :authenticate_user!, :except => [:visit]

  def item
    @klass = params[:type] ? params[:type].classify.constantize : QrItem
    @item = @klass.find_by_id(params[:id]) || @klass.new 
    @item.user = current_user
    @item.prepare
    if request.post?
      @item.save_properties!(params[params[:type]]) 
      redirect_to qr_items_list_url(:type => params[:type])
      return true
    end
    render :action => :form
  end

  def list
    @klass = params[:type] ? params[:type].classify.constantize : QrItem
    @items = @klass.where(:user_id => current_user.id)
  end

  def visit
    @item = QrItem.find(params[:id])
    @item.increment!(:visit)
    @item.prepare
    case @item.type
      when 'Vcard' 
        then send_data(
          @item.qr_data,
          :filename => 'vcard.vcf', 
          :type => 'text/x-vcard',
          :disposition => 'attachment')
      when 'WebUrl' then redirect_to @item.get_url
      when 'SimpleText' then render :simple_text, :layout => 'mobile'
      when 'SmsMessage' then render :sms_message, :layout => 'mobile'
    end
  end

  def destroy
    item = QrItem.find(params[:id])
    item.destroy
    redirect_to :action => :list, :type => item.type.underscore
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    @events = current_user.events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/qr_items_helper.rb
module QrItemsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br />
    <%= f.datetime_select :event_date %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h2>Редактирование события</h2>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h2>События</h2>

<table>
  <tr>
    <th>Событие</th>
    <th>Дата</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.name, event %></td>
    <td><%= l event.event_date, :format => :short %></td>
    <td><%= link_to 'Редактировать', edit_event_path(event) %></td>
    <td><%= link_to 'Удалить', event, :confirm => 'Вы уверены?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новое событие', new_event_path %>

app/views/events/new.html.erb
<h2>Новое событие</h2>

<%= render 'form' %>

<%= link_to 'Назад', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Название:</b>
  <%= @event.name %>
  <br/>
  <b>Дата события:</b>
  <%= l @event.event_date, :format => :short %>
</p>

<p>
<table>
<% @event.event_points.each do |p| %>
  <tr>
    <td style="width:100px;"><%= p.point.address %></td>
    <td style="width:20px;"><%= p.visit_number %></td>
    <td style="width:60px;"><%= link_to 'QR код', p.qr_url, :target => "_blank"%></td> 
    <td><%= link_to '[x]', delete_event_point_url(:event_point_id => p.id) %></td>
  </tr>
<% end %>
</table>
</p>

<% if @points.any? %>
  <% form_tag(add_event_point_path) do %>
    <%= select_tag "points", options_from_collection_for_select(@points, "id", "address") %>
    <%= submit_tag 'Добавить место' %>
  <% end %>
<% end %>

<p>

</p>

<%= link_to 'Редактировать', edit_event_path(@event) %> |
<%= link_to 'Назад', events_path %>

app/views/events/visit_point.html.erb
<% if @event_point %>
  <p>
  <% if @unique %>
    Вы на этой странице в первый раз 
  <% else %>
    Вы уже были на этой странице
  <% end %>
  </p>
  Вы отсканировали код, размещенный по адресу <%= @event_point.point.address %>
  <br/><br/>
  <%=sanitize @event_point.event.description.gsub(/\r/, '<br />') %>
  <br/><br/>
  <% if @chance %>
    Код вашей скидки <%=  10000 + rand(10000) %>
  <% else %>
    Вам не повезло, вероятность получения скидки 1 к 2
  <% end %>
<% else %>
  Такой записи не существует
<% end%>

app/views/home/about.html.erb
<h2>Про проект</h2>
&nbsp;&nbsp;&nbsp;В 2010 году QR коды стали одним из основных трендов в медиабизнесе западного мира. Их популярность возросла в течение года в 17 раз, таким образом выведя данный инструмент из мира промышленной логистики и головоломок от умников в широкие массы рядовых потребителей товаров и услуг.
Такое положение вещей не могло не повлиять на цифровой рынок Украины и России. Применение QR кодов на наших просторах набирает обороты, но пока такие случаи носят стихийный характер, а цели и средства таких кампаний не всегда хорошо продуманы рекламщиками. Это влияет на опыт потребителя не лучшим образом.
<br/><br/>
&nbsp;&nbsp;&nbsp;Упорядочить и развить мир матричных кодов - основные цели сервиса QR it in.Для этого мы создаем специальные инструменты для работы с баркодами - от распространенных общих, до узкоспециализированных отраслевых. Наша платформа будет надежно работать на вас и поможет создавать, редактировать и сохранять 2D коды, с нами вы избавитесь от многих проблем рутинной работы.
<br/><br/>
&nbsp;&nbsp;&nbsp;Если вы хотите получить больше информации о возможностях QR кодов в рекламе и бизнесе, о реальных мероприятиях где матричные коды играют ключевую роль и просто узнать о самих принципах работы технологии - следите за новостями в нашем блоге <a href="http://qr.org.ua/">qr.org.ua</a>

app/views/home/about.uk.html.erb
<h2>Про проект</h2>
&nbsp;&nbsp;&nbsp;В 2010 році QR коди стали одним із основних трендів у медіа бізнесі західного світу. Їх популярність зросла протягом року в 17 разів, таким чином вивівши даний інструмент зі світу промислової логістики і головоломок від розумників у широкі маси пересічних споживачів товарів та послуг.
Таке положення речей не могло не вплинути на цифровий ринок України і Росії. Застосування QR кодів на наших просторах набирає обертів, але поки що такі випадки носять стихійний характер, а цілі і засоби таких кампаній не завжди гарно продумані рекламщиками. Це впливає на досвід споживача не найкращим чином.
<br/><br/>
&nbsp;&nbsp;&nbsp;Впорядкувати і розвинути світ матричних кодів - основні цілі сервісу QR it in. Для цього ми створюємо спеціальні інструменти для роботи із баркодами - від розповсюджених загальних, до вузько спеціальзованих галузевих. Наша платформа надійно працюватиме на вас і допоможе створювати, редагувати і зберігати 2D коди, з нами ви позбудетесь багатьох проблем рутинної роботи.
<br/><br/>
&nbsp;&nbsp;&nbsp;Якщо ви хочете отримати більше інформації про можливості QR кодів у рекламі та бізнесі, про реальні заходи де матричні коди відіграють ключову роль і просто більше дізнатись про самі принципи роботи технології - слідкуйте за новинами в нашому блозі qr.org.ua

app/views/home/contact.html.erb
<h2>Наши контакты</h2>
khomenko.ivan@gmail.com
<br/>
+380 99 548 19 24 

app/views/home/index.html.erb
<h2>QRit.in - сервис для работы с матричными кодами.</h2>
<%= link_to 'Зарегистрируйтесь', new_user_registration_path %> и вы сможете:
<ul>
<li>создавать</li>
<li>редактировать</li>
<li>хранить</li>
</ul>
QR коды, следить за статистикой их считывания.
<br/>
Вместе с нами ваша жизнь станет проще!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QR it</title>
  <%= stylesheet_link_tag 'style' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

	<div id="content">

		<div class="header">
      <div class='searchform'>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <a class="logo" href="/">
        <h1>QR it</h1>
        <i>alpha</i>
      </a>
		</div>

		<div class="subheader">
			<div class="subheader_right">
        <div style="float:left">
          <%= link_to 'Главная', '/' %>
          <%= link_to 'О проекте', '/about' %>
          <%= link_to 'Контакты', '/contact' %>
        </div>
        <div style="float:right">
          <% if current_user %>
            <%= current_user.email + ',' %>
            <%#= link_to 'События', events_path %>
            <%#= link_to 'Места', points_path %>
            <%= link_to 'Выйти', :destroy_user_session %>
          <% end %>
        </div>
     </div>
     <!-- <div class="subheader_left"> <a href="#">Text!</a> </div> -->
		</div>
  						
		<div class="right">
		<!--	<div class="info"> <a class="info" href="#nogo"></a> </div> <p>Text.</p> -->
		  <%= yield %>	
      <!-- <div class="right_left"> </div> <div class="right_right"> </div> -->
		</div>
		<div class="left">
      <% if current_user %>
        <h2>Блок инструментов</h2>
        <p><%= link_to 'Визитки', qr_items_list_path(Vcard.name.underscore) %></p>
        <p><%= link_to 'Смс',     qr_items_list_path(SmsMessage.name.underscore) %></p>
        <p><%= link_to 'Текст',   qr_items_list_path(SimpleText.name.underscore) %></p>
        <p><%= link_to 'Ссылки',  qr_items_list_path(WebUrl.name.underscore) %></p>
      <% else %>
        <p><%= link_to 'Войти', new_user_session_path %></p>
        <p><%= link_to 'Зарегистрироваться', new_user_registration_path %></p>
      <% end %>
		</div>
		
		<div class="footer">
			<p><a href="/">Главная</a> | <a href="/about">О проекте</a> | <a href="/contact">Контакты</a></p>	
			<p>© Copyright 2011, <a href="/">QR it</a> | WiseAdvise </p>
		</div>
	</div>
</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QR it</title>
  <%= csrf_meta_tag %>
</head>
<body>
  <h1>QR it</h1>
  <%= yield %>
  <br/>
  <br/>
  Спасибо что распознали наш код!
</body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Адрес<br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h2>Редактирование адреса</h2>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h2>Рекламные адреса</h2>
<table>
  <tr>
    <td style="width:150px;">
      <table>
        <tr>
          <th>Адрес</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      <% @points.each do |p| %>
        <tr>
          <td style="width:90%;"><%= link_to p.address, edit_point_path(p) %></td>
          <td><%= link_to '[x]', p, :confirm => 'Вы уверены?', :method => :delete %></td>
        </tr>
      <% end %>
      </table>
    </td>
    <td>
      <%= render 'form' %>
    </td>
  </tr>
</table>


<br />

app/views/qr_items/_simple_text.html.erb
<tr>
  <td><%= form.label :text %></td>
  <td><%= form.text_area :text, :rows => 4, :cols => 25 %></td>
</tr>

app/views/qr_items/_sms_message.html.erb
<tr>
  <td><%= form.label :phone %></td>
  <td><%= form.text_field :phone %></td>
</tr>
<tr>
  <td><%= form.label :message %></td>
  <td><%= form.text_area :message, :rows => 4, :cols => 25 %></td>
</tr>

app/views/qr_items/_vcard.html.erb
<% %w{first_name last_name email phone}.each do |attr_name| %>
  <tr>
    <td><%= form.label attr_name %></td>
    <td><%= form.text_field attr_name.to_sym %></td>
  </tr>
<% end %>

app/views/qr_items/_web_url.html.erb
<tr>
  <td><%= form.label :url %></td>
  <td><%= form.text_field :url %></td>
</tr>

app/views/qr_items/form.html.erb
<table>
  <%= form_for(@item,:as => @item.type.underscore.to_sym, :url => { :action => :item, :id => @item.id }, :html => {:method => :post}) do |f| %>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name%></td>
    </tr>
    <%= render :partial => "#{@item.class.name.underscore}", :locals => {:form => f} %>
    <tr><td><%= f.submit "Сохранить" %></td></tr>
  <% end %>
</table>

app/views/qr_items/list.html.erb
<h2>
  <%= t "activerecord.multi_models.#{@klass.name.underscore}"%>
</h2>
<table cellspacing="10">
  <tr style="text-align:left">
    <th>Имя</th>
    <th>Визиты</th>
    <th></th>
    <th></th>
  </tr>
  <% @items.each do |i| %>
    <tr>
      <td><%= link_to i.item_name, :action => :item, :id => i.id, :type => i.type.underscore %></td>
      <td style="text-align:center"><%= i.visit %></td>
      <td style="width:60px;"><%= link_to 'QR код', i.qr_path, :target => "_blank"%></td> 
      <td><%= link_to '[x]', destroy_qr_item_path(i.id), :method => :delete %></td>
    </tr>
  <% end %>
</table>
<%= link_to "Добавить", qr_item_path(:type => params[:type]) %>

app/views/qr_items/simple_text.html.erb
<%= @item.text %>

app/views/users/dashboard.html.erb
<% @events.each do |e| %>
  <p>
  <%= link_to e.name, edit_event_path(e) %>
  </p>
<% end %>